# This file was generated by GoReleaser. DO NOT EDIT.
cask "itodo" do
  name "itodo"
  desc "Simple TUI todo CLI"
  homepage "https://github.com/dasky92/itodo"
  version "0.0.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "itodo"

  on_macos do
    on_intel do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Darwin_x86_64.tar.gz"
      sha256 "53ca565942d78dc2b69d305a6d6cb37782636027499bbf70b28a35dcfb752736"
    end
    on_arm do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Darwin_arm64.tar.gz"
      sha256 "df6a5250a16798b537840c311d0493f028666fc3dbd1fdf15c4f0e194a0c1b67"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Linux_x86_64.tar.gz"
      sha256 "345e559bd039b346a62ccb87c453aabe94d153fac88b3f8253c82baadf04584c"
    end
    on_arm do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Linux_arm64.tar.gz"
      sha256 "8e1515ea17653d730c4a759f8330d23916e9bcc2d3190255ad20622213235636"
    end
  end

  # No zap stanza required
end
