# This file was generated by GoReleaser. DO NOT EDIT.
cask "itodo" do
  name "itodo"
  desc "Simple TUI todo CLI"
  homepage "https://github.com/dasky92/itodo"
  version "0.0.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "itodo"

  on_macos do
    on_intel do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Darwin_x86_64.tar.gz"
      sha256 "d17be45c1c6759cde2db3f829879f68671bb07a8783df061783f3265dafdb0d0"
    end
    on_arm do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Darwin_arm64.tar.gz"
      sha256 "c726b030fa5432c66e03092d2e9cc723d8322964a0c3f4281dfd83e14cafbaaa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Linux_x86_64.tar.gz"
      sha256 "4abd2c43868bbba85fa66cadcb2398b59c9ca87023359ef2f5a3db87a9bd33c8"
    end
    on_arm do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Linux_arm64.tar.gz"
      sha256 "83c9e632c0d42ac23a6198595db3ddae6a5bd87817260ea9388492eef91b5113"
    end
  end

  # No zap stanza required
end
