# This file was generated by GoReleaser. DO NOT EDIT.
cask "itodo" do
  name "itodo"
  desc "Simple TUI todo CLI"
  homepage "https://github.com/dasky92/itodo"
  version "0.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "itodo"

  on_macos do
    on_intel do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Darwin_x86_64.tar.gz"
      sha256 "3c971672bdffbe592124eb7d453680b7c10f2747d4c9beab5e07fc7ece2f325c"
    end
    on_arm do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Darwin_arm64.tar.gz"
      sha256 "d72f1b3cbea2be24103f032d8e2b670839db8ab31567f208fe6c253c664b8ec6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Linux_x86_64.tar.gz"
      sha256 "2a10c56e178a411d21cf7d59ef5cff93abd4d1d9ba90c8f66e244690a6182e84"
    end
    on_arm do
      url "https://github.com/dasky92/itodo/releases/download/v#{version}/itodo_Linux_arm64.tar.gz"
      sha256 "138ffd42696eb99d73dfb6283b7f8169eaee5b936a71d618bcf320d635b7a33b"
    end
  end

  # No zap stanza required
end
